apiVersion: v1
kind: Secret
metadata:
  annotations:
    serving.kserve.io/s3-endpoint: s3.us-east-2.amazonaws.com/
    serving.kserve.io/s3-region: us-east-2
    serving.kserve.io/s3-useanoncredential: 'false'
    serving.kserve.io/s3-usehttps: '1'
  name: models-bucket-secret
stringData:
  AWS_ACCESS_KEY_ID: {{ aws_access_key_id }}
  AWS_SECRET_ACCESS_KEY: {{ aws_secret_access_key}}
