apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  annotations:
    serving.kserve.io/deploymentMode: RawDeployment
    serving.kserve.io/enable-prometheus-scraping: 'true'
  labels:
    opendatahub.io/dashboard: 'true'
  name: ministral-3b-instruct
spec:
  predictor:
    minReplicas: 1
    model:
      args:
      - --dtype=bfloat16
      - --model=/mnt/models
      - --uvicorn-log-level=debug
      - --served-model-name=ministral-3b-instruct
      - --max-model-len=10
      env:
      - name: HF_HUB_CACHE
        value: /tmp
      modelFormat:
        name: pytorch
      resources:
        limits:
          memory: 28Gi
        requests:
          cpu: '12'
          memory: 28Gi
      runtime: vllm-runtime
      storageUri: s3://odh-bucket/models/ministral-3b-instruct
      volumeMounts: null
    serviceAccountName: modelmesh-serving-sa
    volumes: null
