apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  annotations:
    serving.kserve.io/deploymentMode: RawDeployment
    serving.kserve.io/enable-prometheus-scraping: 'true'
  labels:
    opendatahub.io/dashboard: 'true'
  name: mistral-7b-v3
spec:
  predictor:
    minReplicas: 1
    model:
      args:
      - --dtype=bfloat16
      - --model=/mnt/models
      - --uvicorn-log-level=debug
      - --chat-template=/app/data/template/template_chatml.jinja
      - --served-model-name=mistral-7b-v3
      - --max-model-len=2048
      - --max-model-len=10
      env:
      - name: HF_HUB_CACHE
        value: /tmp
      modelFormat:
        name: pytorch
      resources:
        limits:
          memory: 70Gi
        requests:
          cpu: '13'
          memory: 64Gi
      runtime: vllm-runtime
      storageUri: s3://ods-ci-wisdom/mistralai/Mistral-7B-Instruct-v0.3/
      volumeMounts: null
    serviceAccountName: modelmesh-serving-sa
    volumes: null
