apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  annotations:
    serving.kserve.io/deploymentMode: RawDeployment
    serving.kserve.io/enable-prometheus-scraping: 'true'
  labels:
    opendatahub.io/dashboard: 'true'
  name: granite-2b-instruct-4k
spec:
  predictor:
    minReplicas: 1
    model:
      args:
      - --dtype=bfloat16
      - --model=/mnt/models
      - --uvicorn-log-level=debug
      - --served-model-name=granite-2b-instruct-4k
      - --max-model-len=4
      env:
      - name: HF_HUB_CACHE
        value: /tmp
      modelFormat:
        name: pytorch
      resources:
        limits:
          memory: 15Gi
        requests:
          cpu: '8'
          memory: 14Gi
      runtime: vllm-runtime
      storageUri: s3://ods-ci-wisdom/granite-2b-instruct-preview-4k-r240917a/
      volumeMounts: null
    serviceAccountName: modelmesh-serving-sa
    volumes: null
